language: node_js
node_js:
  - "node"
  - 6
  - 8
  - 9
after_success:
  - npm install -g codecov
  - cat test/unit/coverage/lcov.info
  - codecov --file test/unit/coverage/lcov.info --disable search
