language: node_js
node_js:
  - "node"
  - 6
  - 8
  - 9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
after_success:
  - npm install -g codecov
  - codecov -f test/unit/coverage/lcov.info
